# permissions for end users to edit customcompositions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customcomposition-editor-role
rules:
- apiGroups:
  - poc.sergenyalcin.io
  resources:
  - customcompositions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - poc.sergenyalcin.io
  resources:
  - customcompositions/status
  verbs:
  - get
