apiVersion: v1
kind: Pod
metadata:
  name: xrm-test-label-annotation
  labels:
    app: xrm
spec:
  containers:
    - name: set-label-and-annotation
      image: sergenyalcin10/xrm-runner:3.0-alpha
      command: ['sh', '-c', '/runner sergenyalcin10/set-label-xrm:1.0-alpha sergenyalcin10/set-annotation-xrm:2.0-alpha < /go/src/resources/resourceList.yaml && sleep infinity']
