apiVersion: v1
kind: Pod
metadata:
  name: krm-test
  labels:
    app: krm
spec:
  containers:
    - name: debug-resources
      image: sergenyalcin10/custom-composition-poc:2.0-alpha
      command: ['sh', '-c', 'sleep infinity']
      volumeMounts:
        - name: ex-storage
          mountPath: /data/
  initContainers:
    - name: prep-resources
      image: sergenyalcin10/custom-composition-poc:2.0-alpha
      command: ['sh', '-c', 'wget https://raw.githubusercontent.com/sergenyalcin/custom-composition-poc/main/resources/resource1.yaml -O /data/resource1.yaml &&
      wget https://raw.githubusercontent.com/sergenyalcin/custom-composition-poc/main/resources/resource2.yaml -O /data/resource2.yaml ']
      volumeMounts:
        - name: ex-storage
          mountPath: /data/
    - name: set-annotation
      image: sergenyalcin10/custom-composition-poc:2.0-alpha
      command: ['sh', '-c', 'kpt fn eval /data --exec /set-annotations -- key=value']
      volumeMounts:
        - name: ex-storage
          mountPath: /data/
    - name: set-first-label
      image: sergenyalcin10/custom-composition-poc:2.0-alpha
      command: [ 'sh', '-c', 'kpt fn eval /data --exec /set-labels -- app=poc' ]
      volumeMounts:
        - name: ex-storage
          mountPath: /data/
    - name: set-second-label
      image: sergenyalcin10/custom-composition-poc:2.0-alpha
      command: [ 'sh', '-c', 'kpt fn eval /data --exec /set-labels -- release=demo' ]
      volumeMounts:
        - name: ex-storage
          mountPath: /data/
  volumes:
    - name: ex-storage
      emptyDir: {}